### ISSUE TITLE
Documentation of game parameters, observations, actions

### ISSUE THREAD

**Issue by raphCode** [google-deepmind/open_spiel#1090]
During my usage of openspiel, I encountered difficulties finding detailed documentation on game parameters, observations, and actions.
Specifically, there is no clear list of parameters accepted by each game, and I had to search through the C++ code to find them.
Furthermore, it is challenging to determine which observations are available to agents without guessing based on Tensor shapes or content. This makes it very hard to comprehend whether the agent can even learn something reasonable based on the available information.

A very specific case is the game `coop_box_pushing`, which is advertised as a perfect information game by the docs. In the default configuration however, the observation includes only a single field in front of the agent. One needs to discover the game may take an `fully_observable` parameter which actually makes the observation perfect information.

Would it be possible to include this information in the docs? Maybe it is already there, and I was not able to find it?
It would also be acceptable if the documentation pages link to the relevant C++ code with explaining comments.

The bottom-line is: I find it highly surprising that a python-faced project with an `readthedocs.io` page has very little usable documentation*, and expects users to examine various code examples and the C++ source to collect information.

*Part of my frustration is that I started my project before there was even a core API documentation available, requiring hours of reverse engineering the API in an `ipython` console.

**Comment by lanctot** [comment]
Yeah, the documentation can always be improved. 

We have a video tutorial linked from the main page: that, and the API reference, are the best ways to understand the core API. Some other functions may require reading function headers in spiel.h.

Regarding observations, you didn't miss it. They are documented in the headers of the C++ source files. Unfortunately we often don't have the time to improve the docs due to other higher priorities, but could really use the community's help with this! 

I like the idea of linking to the section of the C++ header from the games page. Can you submit a PR?

**Comment by raphCode** [comment]
> I like the idea of linking to the section of the C++ header from the games page. Can you submit a PR?

I will try to find some time. Currently I am busy with my thesis, so that could take a while.

How would this best be done without increasing the maintenance burden? Can we autogenerate docs from the code / using a helper script?

**Comment by lanctot** [comment]
This would be wonderful and still welcome, but I'm closing the issue for now due to inactivity.
