### ISSUE TITLE
Loading coop_box_pushing game as turn-based flattens observation tensor

### ISSUE THREAD

**Issue by raphCode** [google-deepmind/open_spiel#1096]
Basically, the bug (or the thing I don't understand) is this discrepancy:
```python
pyspiel.load_game("coop_box_pushing", dict(fully_observable=True)).observation_tensor_shape()
# returns [11, 8, 8]
pyspiel.load_game_as_turn_based("coop_box_pushing", dict(fully_observable=True)).observation_tensor_shape()
# returns [708]
```

**Comment by lanctot** [comment]
Hmm.... ah yes, see here: https://github.com/deepmind/open_spiel/blob/efa004d8c5f5088224e49fdc198c5d74b6b600d0/open_spiel/game_transforms/turn_based_simultaneous_game.h#L107

Wow, we wrote that a long time ago, I haven't seen it in a while. I think the reasoning behind that choice went something like: when you represent a simultaneous game as turn-based, you need to encode the intermediate steps as observations/information states to each player, and the player who is observing it should know who they are. So you add this information to the tensor (and there's no easy way to do it unless you flatten it). This avoids collisions in the observations across players, which could be important if you're using one table to represent a joint policy (as e.g. CFR does) or one neural network for both players.

In retrospect, there are times where this does not make sense-- like (presumably) your setting-- and we should make it optional (and maybe not even the default, at least not for the tensor functions which are normally used in RL).  And we can implement the old behavior easily via a flag sent to the game transform itself. 

Do you feel up to implementing it? If not, I'd be happy to do it, but it may take time because I'm quite busy at the moment.

**Comment by raphCode** [comment]
Ah, good to know it is intended behavior, not a bug.

I understand the addition of the player onehot encoding.
However, I think just flattening everything with no good way recover the information is not optimal.

In the case of 2D environments (3D tensors), the spatial relationship between the different grid items usually can be exploited, by e.g. convolutional networks. To use one-hot encodings with convolutional networks, I have seen them implemented as additional image planes filled with either zeros or ones. In other words, the channel dimension of the image tensor is extended.

Using multiple observation tensors (in this case the 2D grid as 3D tensor, and a 1D onehot) would be another way of dealing with this, but I think that requires careful work to ensure API compatibility.
This way the downstream implementation can decide how to handle it.
