### ISSUE TITLE
Adding new game: Catan

### ISSUE THREAD

**Issue by Jazeem** [google-deepmind/open_spiel#1098]
Catan is a very popular and one of the most influential modern style board games. US & World championship events are held for the game.

The game is published under Catan Studio and might not be free to use. But there is an open alternative that's widely used called Colonist (https://colonist.io).

If adding Catan is not possible due to IP reasons. Is it possible to add Colonist?
If possible, I'd love to add it to open_spiel

**Comment by lanctot** [comment]
Having Catan would be great, but yeah it is tricky with the licensing. 

There was an OpenSpiel implementation that wrapped an existing Catan implementation. I would be surprised if that didn't still work because the core API hasn't changed.

See these:

- https://github.com/deepmind/open_spiel/pull/233
- https://github.com/deepmind/open_spiel/issues/192

The author Joel Bokelmann also sent me his Bachelor thesis on the topic. If you contact me, I'd be happy to send it to you.

See also these articles:
- https://akrishna77.github.io/QSettlers/
- https://settlers-rl.github.io/

**Comment by Jazeem** [comment]
Okay. Thanks!
