### ISSUE TITLE
Question: how to evaluate rnad algorithm

### ISSUE THREAD

**Issue by white0721** [google-deepmind/open_spiel#1155]
Hi.
Is there any way to evaluate a model trained with the rnad algorithm against a random agent? (like tic_tac_toe_dqn_vs_tabular.py for example)
In tic_tac_toe_dqn_vs_tabular.py, the action is taken from the return value of the step function (type step_output) and env is transitioned to the next state.
However, the return value of the step function in rnad is of type dect, so I ',m not sure if I can do the same thing in this way.
Is there any better way to do this?

**Comment by lanctot** [comment]
Ok so you can do it, but you need a few steps because the RNaD implementation does not expose the policy as an RNaD agent.

You can get the policy for any state using `action_probabilities`: https://github.com/google-deepmind/open_spiel/blob/7c58b6c28cc975f2a7a02a7ea604197a30ed3186/open_spiel/python/algorithms/rnad/rnad.py#L985 (you can get the state from the environment using `get_state` accessor in rl_environment). Then you can just sample an action from the policy and take a step on the environment using the action.

Hope this helps!

**Comment by white0721** [comment]
Thank you for your reply.
By following your comments, I was able to do what I wanted to do!
It helped, thank you very much.

**Comment by lanctot** [comment]
No problemo, glad it helped!
