### ISSUE TITLE
bug in chess terminal determination?

### ISSUE THREAD

**Issue by XintianHan** [google-deepmind/open_spiel#1160]
I just tried the following code
```
env = pyspiel.load_game("chess")
state = env.new_initial_state()
while not state.is_terminal():
    actions = state.legal_actions(state.current_player())
    spiel_actions = np.array(sorted(actions))
    state.apply_action(spiel_actions[0])
print(str(state))
```
It seems that the game ended earlier before the terminal. I checked the print of the state at the last line. It's 1nbqkbnr/rppppppp/p7/8/8/P7/RPPPPPPP/1NBQKBNR w Kk - 10 7

It does not seem to be the end of the game. What's wrong here? Thanks in advance!

**Comment by lanctot** [comment]
Hi, I think this is because a state is getting repeated 3 times: https://en.wikipedia.org/wiki/Threefold_repetition

Checked by this function: https://github.com/google-deepmind/open_spiel/blob/7c58b6c28cc975f2a7a02a7ea604197a30ed3186/open_spiel/games/chess/chess.h#L178

Use `print(state.debug_string())` throughout the history to see it visually.

**Comment by XintianHan** [comment]
> Hi, I think this is because a state is getting repeated 3 times: https://en.wikipedia.org/wiki/Threefold_repetition
> 
> Checked by this function:
> 
> https://github.com/google-deepmind/open_spiel/blob/7c58b6c28cc975f2a7a02a7ea604197a30ed3186/open_spiel/games/chess/chess.h#L178
> 
> Use `print(state.debug_string())` throughout the history to see it visually.

Thanks! This actually the case!
