### ISSUE TITLE
How to implement a python variation of alpha-beta and test using the framework in WSL

### ISSUE THREAD

**Issue by tonirm2077** [google-deepmind/open_spiel#1169]
I would like to know if the correct way to implement a new variation of alpha-beta using: open_spiel/python/algorithms/minimax.py and minimax_test.py for testing. I would like to know if this is the correct way to do this using WSL

**Comment by lanctot** [comment]
Hi @tonirm2077, 

By WSL do you mean "Windows Subsystem for Linux"? The way to do it is independent of environment.

Yes, that is correct. You can either build on top of or fork and modify minimax.py and minimax_test.py. Is this for personal research, or is the question more because you are considering submitting your code as a PR?

(Because if it's for your own research you can do whatever you want. :) If it's about submitting your variant, then that depends on the variant and how much modifying of the alpha-beta code is required.)

**Comment by lanctot** [comment]
We have moved this discussion to https://github.com/google-deepmind/open_spiel/discussions/1173 so I'm closing this for now.
