### ISSUE TITLE
Block dominoes implementation

### ISSUE THREAD

**Issue by Brunozml** [google-deepmind/open_spiel#1203]
Hi, I'm looking to solve a version of block dominoes for my bachelor's thesis and I would like to contribute to OpenSpiel's implementation (which seems to be incomplete, as tests fail and it is not currently on the list of registered games); However, I'm having trouble grasping how to contribute in this domain.

**Comment by lanctot** [comment]
Hi @Brunozml, 

Block dominoes should be on games list.. here: https://github.com/google-deepmind/open_spiel/blob/1b09f3b9749f29d41aa797bcacb214ef70b6ea1f/open_spiel/python/tests/pyspiel_test.py#L109

It's a python game, so I guess you were not finding it because if the missing `python_` prefix.

Anyway it should be included in the basic game simulations test (python/tests/games_sim_test.py) as well as its own test here: https://github.com/google-deepmind/open_spiel/blob/master/open_spiel/python/games/block_dominoes_test.py. 

Which tests are failing for you? Can you past the errors?

**Comment by Brunozml** [comment]
Hi @lanctot,

Thank you for your reply, I hadn't noticed the `python_` prefix. The errors were due to some tinkering I had been doing to the `block_dominoes.py`  file.
